### ISSUE TITLE
Report with user_key authentication mode

### ISSUE THREAD

**Issue by picsoung** [3scale/3scale_ws_api_for_ruby#20]
Hey,

I tried to report a call like this 

```ruby
@@client.report( {:user_key => params[:user_key],  :usage => {method_name => usage_value}})
```

But in my error tabs on my dashboard there is the following error
`application with id="" was not found`

and the call is not reported on this metric.

I will try to fork and PR, just no time right now.
Thanks

**Comment by picsoung** [comment]
Did we have an update on this? ping @mikz 
I kind of forgot since last time...

**Comment by andrewdavidmackenzie** [comment]
plugin code owner is not engineering, but support @picsoung

**Comment by vdel26** [comment]
The problem seems to be because we are hardcoding the parameter name of the key to `app_id` here: 
https://github.com/3scale/3scale_ws_api_for_ruby/blob/master/lib/3scale/client.rb#L271

Whereas in other plugins we just use any parameter name the user passes when calling the `report` method.

**Comment by mikz** [comment]
@vdel26 kind of, the `append_encoded_value` does not append nil values, so it is saying: if you gave us these parameters, append them.
It is just matter of just adding `:user_key` there. And then probably extracting all those to a constant.
