### ISSUE TITLE
Specify a minimum Ruby version in the gemspec

### ISSUE THREAD

**Issue by davidor** [3scale/3scale_ws_api_for_ruby#27]
Travis is currently failing on master for all the ruby versions that Travis tries except 2.3.0. In the gemspec, there isn't a rack version specified, so Travis downloads the latest one (2.0.1), which requires ruby >= 2.2.2.

I think the ideal solution is to specify a minimum ruby version in the gemspec, and then, specify a rack version accordingly.

**Comment by mikz** [comment]
We don't really depend on a ruby version. If we fail with rack 2.0, we should lock rack to ~> 1.x version.

**Comment by mikz** [comment]
That would not really help. We should use [appraisal](https://github.com/thoughtbot/appraisal) to lock rack on old rubies to older version when bundler is not so smart to figure it out.

**Comment by davidor** [comment]
Updating bundler does not help.
Locking to rack < 2.0.0 works. Because the ruby >= 2.2.2 dependency was introduced in rack v2.
I fail to see how Appraisal would help here. We could define different gemfiles with different versions of rack but some of them would fail with older rubies.

**Comment by mikz** [comment]
We would test with rack 1.x on all rubies and with rack 2.x on ruby >= 2.2.2. 
And use travis matrix to not run Rack 1.x with Ruby < 2.2.2
